baseURL = "https://zmvx.gitee.io/"
# baseURL = "https://zeidiao.github.io/"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
title = "贼雕"                         # site title  # 网站标题
theme = "zozo"
hasCJKLanguage = true                  # has chinese/japanese/korean ?  # 自动检测是否包含 中文\日文\韩文
summaryLength = 100
paginate = 4                           # shows the number of articles  # 首页显示文章数量
enableEmoji = true
googleAnalytics = ""                   # your google analytics id
disqusShortname = ""                   # your discuss shortname

pygmentsUseClasses = true
pygmentCodeFences = true
pygmentscodefencesguesssyntax = true

[author]                               # essential                     # 必需
  name = "ZeiDiao"

[blackfriday]
  smartypants = false

[[menu.main]]                          # config your menu  # 配置菜单
  name = "Home" #首页
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Archive"  # 归档
  weight = 20
  identifier = "archive"
  url = "/posts/"
[[menu.main]]
  name = "Tags" # 标签
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "books" # 书单
  weight = 31
  identifier = "books"
  url = "/books/"
[[menu.main]]
  name = "About"  # 关于
  weight = 40
  identifier = "about"
  url = "/about/"

[params]
  subTitle = "zeidiao, student | developer"                                       # site's subTitle  # 网站二级标题
  footerSlogan = "Be prepared for a long struggle"                                   # site's footer slogan  # 网站页脚标语
  keywords = ["zeidiao","贼雕","hugo","威远","白塔小学"]                                  # site's keywords  # 网站关键字
  description = "贼雕的个人博客,记录我的技术成长路"                        # site's description  # 网站描述
  enableMathJax = true                                                 # enable mathjax  # 是否使用mathjax（数学公式）
  enableSummary = true                                                 # display the article summary  # 是否显示文章摘要
  mainSections = ["posts","post"]
  
# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[params.valine]
  enable = false
  appId = ""
  appKey = ""
  placeholder = " "
  visitor = true

# Your socail's url
[social]
  github = "https://github.com/zeidiao"
  twitter = "https://twitter.com/zeidiao"
  bilibili = "https://space.bilibili.com/490181478/"
  medium = "https://medium.com/@zeidiao"
  #facebook = " "
  weibo = "https://weibo.com/zeidiao"
  instagram = "https://instagram.com/zeidiao"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

