name: CI  # 自动化的名称

on:
  push: # push的时候触发
    branches: [ master ]  # 那些分支需要触发

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest  # 镜像市场

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout # 步骤的名称
        uses: actions/checkout@v2 #软件市场的名称
        with: # 参数
          submodules: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: ""  #optional, default is latest
          extended: true
      - name: Build
        run: hugo -D -t zozo --baseURL=https://zeidiao.github.io/ # 编译静态页面文件,-t 指定了主题, --baseURL 指定了站点监听的域名
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.6.4
        with:
          # deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }} # 这里的 ACTIONS_DEPLOY_KEY 则是上面设置 Private Key的变量名
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: zeidiao/zeidiao.github.io # Pages 远程仓库 
          publish_dir: ./public
          keep_files: false # remove existing files
          publish_branch: master  # deploying branch
          commit_message: ${{ github.event.head_commit.message }}



# name: CI #自动化的名称
# on:
#   push: # push的时候触发
#     branches: # 那些分支需要触发
#       - master
# jobs:
#   build:
#     runs-on: ubuntu-latest # 镜像市场
#     steps:
#       - name: checkout # 步骤的名称
#         uses: actions/checkout@v1 #软件市场的名称
#         with: # 参数
#           submodules: true
#       - name: Setup Hugo
#         uses: peaceiris/actions-hugo@v2.2.2
#         with:
#           hugo-version: '0.64.1'
#           extended: true
#       - name: Build
#         run: hugo -D
#       - name: Deploy
#         uses: peaceiris/actions-gh-pages@v2.5.1
#         env:
#           ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
#           EXTERNAL_REPOSITORY: zeidiao/zeidiao.github.io
#           PUBLISH_BRANCH: master
#           PUBLISH_DIR: ./public
